# spring:
#   datasource:
# #    driver-class-name: org.postgresql.Driver
#     url: jdbc:h2:mem:homedb
#     username: sa
#     password:

#   jpa:
#     hibernate:
#       ddl-auto: update
# #    properties:
# #      hibernate:
# #        dialect: org.hibernate.dialect.

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/erental
    username: wesley
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect